### ISSUE TITLE
undefined method `setup_argv' for Test::Unit:Module

### ISSUE THREAD

**Issue by trcarden** [sporkrb/spork-testunit#18]
Looks like the setup_argv method isn't available. I am running ruby 1.9.2 and rails 3.1.rc4. Here is the backtrace

/Users/trcarden/.rvm/gems/ruby-1.9.2-p180@global/gems/spork-testunit-0.0.5/lib/spork/test_framework/test_unit.rb:20:in `run_tests'
/Users/trcarden/.rvm/gems/ruby-1.9.2-p180@global/gems/spork-0.8.5/lib/spork/run_strategy/forking.rb:13:in`block in run'
/Users/trcarden/.rvm/gems/ruby-1.9.2-p180@global/gems/spork-0.8.5/lib/spork/forker.rb:21:in `block in initialize'
/Users/trcarden/.rvm/gems/ruby-1.9.2-p180@global/gems/spork-0.8.5/lib/spork/forker.rb:18:in`fork'
/Users/trcarden/.rvm/gems/ruby-1.9.2-p180@global/gems/spork-0.8.5/lib/spork/forker.rb:18:in `initialize'
/Users/trcarden/.rvm/gems/ruby-1.9.2-p180@global/gems/spork-0.8.5/lib/spork/run_strategy/forking.rb:9:in`new'
/Users/trcarden/.rvm/gems/ruby-1.9.2-p180@global/gems/spork-0.8.5/lib/spork/run_strategy/forking.rb:9:in `run'
/Users/trcarden/.rvm/gems/ruby-1.9.2-p180@global/gems/spork-0.8.5/lib/spork/server.rb:47:in`run'
/Users/trcarden/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/drb/drb.rb:1558:in `perform_without_block'
/Users/trcarden/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/drb/drb.rb:1518:in`perform'
/Users/trcarden/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/drb/drb.rb:1592:in `block (2 levels) in main_loop'
/Users/trcarden/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/drb/drb.rb:1588:in`loop'
/Users/trcarden/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/drb/drb.rb:1588:in `block in main_loop'

**Comment by avakhov** [comment]
The same with 1.9.3-preview1 and rails-3.0.10

**Comment by oriolgual** [comment]
See #17

**Comment by avakhov** [comment]
@oriolgual thanks! I use your solution already.

**Comment by timcharper** [comment]
Gopal Patel (nixme), the super awesome new maintainer of this gem, has merged a pull request that should resolve this.

**Comment by rmm5t** [comment]
It would be great if we could get a release that incorporates this fix too.

**Comment by ncri** [comment]
Hi, I still get the same error. I use the latest gem straight from github:

```
undefined method `setup_argv' for Test::Unit:Module
/Users/nico/.rvm/gems/ruby-1.9.2-p290/gems/spork-testunit-0.0.7/lib/spork/test_framework/test_unit.rb:29:in `run_tests'
```

Trying to use this with guard-test, in a Rails 3.1.1 app.

**Comment by rmm5t** [comment]
@ncri, 

You said you're using the "latest gem straight from github."  Are you building the gem yourself or just using the 0.0.7 gem from rubygems? Otherwise, I think your path to spork-testunit would be different in your trace if you had a `:git` directive pointing at HEAD in your Gemfile.  The fix from #17 still isn't in a versioned release.

Also, Ruby 1.9 is actually MiniTest under the hood, not really Test::Unit.  You probably want to use `guard-minitest` instead of `guard-test`.

Here's what I currently use as my set of dependencies to get guard and spork working in a MiniTest/Test::Unit environment for Rails 3.x and Ruby 1.9.x:

```
gem "guard-minitest"
gem "rb-fsevent"
gem "spork", "~> 0.9.0.rc9"
gem "spork-testunit"
gem "guard-spork"
```

**Comment by ncri** [comment]
Thanks for the instructions, I will test your setup! And yes, I'm using the git directive to point to spork-testunit here on github. This should give me the absolute latest version I assume?

**Comment by ncri** [comment]
Okay, thx, your setup works for me. Well, there are still issues, but generally it works. ;-)

About Minitest: Does it mean ruby 1.9 cannot use the test-unit gem? Is it always using Minitest automatically?

**Comment by rmm5t** [comment]
@ncri, You should be able to use the test-unit gem as an override. It's not something I do though. I merely rely on the Test::Unit wrapper libs that MiniTest provides (well, that the standard library provides) to emulate Test::Unit.

**Comment by nixme** [comment]
We'll be splitting up minitest support into it's own **spork-minitest** gem in the next couple of days so that test framework detection is less brittle.

**Comment by ncri** [comment]
@rmm5t well, I had the test unit-gem in my gemfile but i think for some reason still minitest was used. Well, anyway, I removed test-unit now and that fixes some issues I had with my test output. Is there any reason to use test-unit instead of mini-test? ;-)

Another question, anyone knows how to run all the tests with guard-spork/guard-minitest? And how to get growl notifications? 

@nixme: Sounds great, thanks for working on this. ;-)

**Comment by tubbo** [comment]
@nixme any ETA on that minitest gem? this still isn't working for me. here's what I got in my Gemfile:

```
gem 'growl'
gem 'rb-fsevent'
gem 'guard-minitest'
gem 'spork', '~> 0.9.0.rc9'
gem 'spork-testunit'
gem 'guard-spork'
```

**Comment by rmm5t** [comment]
@tubbo, Try v0.8.x of guard.  I had trouble with the guard 0.9.x myself. I haven't tried guard 0.10 yet.

```
gem "guard", "~> 0.8.8" # 0.9.1 doesn't seem to work
gem "guard-minitest"
gem "rb-fsevent"
gem "spork", "~> 0.9.0.rc9" # waiting for official release
gem "spork-testunit"
gem "guard-spork"
```

**Comment by tubbo** [comment]
@rmm5t it actually worked for me when i specified the git repo rather than a version number. but if that fails later on, i'll try setting the guard version to ~> 0.8.8

**Comment by rmm5t** [comment]
@tubbo Thanks. guard 0.10 now does the trick too.
